checking/urls.py
from django.urls import path

from checking.apps import CheckingConfig
from checking.views import QuestionsView

app_name = CheckingConfig.name

urlpatterns = [
    path('<int:pk>/questions/', QuestionsView.as_view(), name='questions'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('materials.urls', namespace='materials')),
    path('checking/', include('checking.urls', namespace='checking')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import HomeListView, MaterialsView, MaterialDetailView

app_name = MaterialsConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('chapters/<int:pk>/materials/', MaterialsView.as_view(), name='materials'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='material-detail'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, UserUpdateView, ResetPasswordView

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("registration/", RegisterView.as_view(), name="register"),

    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("password-reset/", ResetPasswordView.as_view(), name="password-reset"),
]

materials/models.py
from django.db import models

from users.models import NULLABLE


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Название раздела",
        help_text="Укажите название раздела",
    )
    description = models.TextField(
        verbose_name="Описание раздела", help_text="Укажите описание раздела", **NULLABLE
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"


class Material(models.Model):
    title = models.CharField(
        max_length=150,
        help_text="Укажите название материала",
        verbose_name="Название материала",
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name="materials",
        help_text="Выберите раздел",
        verbose_name="Раздел",
        **NULLABLE,
    )

    contents = models.TextField(
        verbose_name="Содержание материала", help_text="Укажите содержание материала", **NULLABLE
    )
    image = models.ImageField(
        upload_to="materials/preview",
        verbose_name="Превью",
        help_text="Загрузите фото",
        **NULLABLE,
    )

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Материал"
        verbose_name_plural = "Материалы"

materials/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from materials.models import Category, Material
from django.views.generic import View, ListView, DetailView


class HomeListView(ListView):
    model = Category
    template_name = 'materials/index.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Category.objects.all()


class MaterialsView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        category = Category.objects.get(pk=pk)
        materials = Material.objects.filter(category=category)
        context = {
            "materials": materials,
        }
        return render(request, 'materials/materials.html', context)


class MaterialDetailView(LoginRequiredMixin, DetailView):
    model = Material

materials/templates/materials/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">-->
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    {% include 'materials/includes/inc_menu.html' %}
</header>

<main role="main">
    <div class="container">
        {% block content %}
        {% endblock %}

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            {% include 'materials/includes/inc_footer_menu.html' %}
        </footer>
    </div>
</main>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

materials/templates/materials/index.html
{% extends 'materials/base.html' %}
{% block content %}
{% load my_tags %}

<div class="row text-center">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">
                <p>{{ object.description }}</p>
                <a href="{% url 'materials:materials' object.pk %}">
                    <button type="button" class="btn btn-sm btn-outline-primary">К материалам</button>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'materials/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <img src="{{ object.image | media_filter }}" alt="Material Image" class="img-fluid">
        <div class="card-body">
            <div class="card-body">
                <p>{{ object.contents }}</p>
            </div>
            <a href="{% url 'checking:questions' object.pk %}">
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">Пройти тестирование</button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/materials.html
{% extends 'materials/base.html' %}
{% block content %}
{% load my_tags %}

<div class="row text-center">
    {% for material in materials %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ material.title }}</h4>
            </div>
            <img src="{{ material.image | media_filter }}" alt="Material Image" class="img-fluid">
            <div class="card-body">
                <p>{{ material.contents | truncatechars:100 }}</p>
                <a href="{% url 'materials:material-detail' material.pk %}">
                    <button type="button" class="btn btn-sm btn-outline-primary">Подробнее</button>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}