config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('materials.urls', namespace='materials')),
    path('checking/', include('checking.urls', namespace='checking')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, UserUpdateView, ResetPasswordView

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("registration/", RegisterView.as_view(), name="register"),

    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("password-reset/", ResetPasswordView.as_view(), name="password-reset"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Create your models here.
class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name="Email")

    avatar = models.ImageField(upload_to="users/avatar/", verbose_name="Аватар", **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name="Номер телефона", **NULLABLE)
    country = models.CharField(max_length=35, verbose_name="Страна", **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm


from checking.forms import StyleFormMixin
from users.models import User


class RegistrationForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar', 'phone', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class ResetPasswordForm(StyleFormMixin, PasswordResetForm):
    class Meta:
        model = User
        fields = ("email",)

users/views.py
import random

from django.contrib.auth.hashers import make_password
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from config import settings
from users.forms import RegistrationForm, UserForm, ResetPasswordForm
from users.models import User


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = "users/register.html"

    def get_success_url(self):
        return reverse('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = True
        user.save()
        return super().form_valid(form)


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


class ResetPasswordView(PasswordResetView):
    email_template_name = 'users/reset_password.html'
    form_class = ResetPasswordForm
    template_name = 'users/reset_password.html'

    def get_success_url(self):
        return reverse('users:login')

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        user = User.objects.get(email=email)

        password = ''.join([str(random.randint(0, 9)) for _ in range(8)])
        user.password = make_password(password)
        user.save()
        message = f"Ваш новый пароль: {password}"
        send_mail(
            subject="Смена пароля",
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False,
        )
        return super().form_valid(form)

users/templates/users/login.html
{% extends 'materials/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Войти
                    </button>
                    <a href="{% url 'users:password-reset' %}" class="btn btn-danger">Восстановление пароля</a>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'materials/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Зарегистрироваться
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/reset_password.html
{% extends 'materials/base.html' %}
{% block content %}

<h1>Восстановление пароля</h1>

<div class="card-body">
<form method="post" class="form-floating" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
        Восстановить пароль
    </button>
</form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'materials/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Мой профиль
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Сохранить
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}