config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('materials.urls', namespace='materials')),
    path('checking/', include('checking.urls', namespace='checking')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from materials.apps import MaterialsConfig
from materials.views import HomeListView, MaterialsView, MaterialDetailView

app_name = MaterialsConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('chapters/<int:pk>/materials/', MaterialsView.as_view(), name='materials'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='material-detail'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, UserUpdateView, ResetPasswordView

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("registration/", RegisterView.as_view(), name="register"),

    path("profile/", UserUpdateView.as_view(), name="profile"),
    path("password-reset/", ResetPasswordView.as_view(), name="password-reset"),
]

materials/models.py
from django.db import models

from users.models import NULLABLE


class Category(models.Model):
    name = models.CharField(
        max_length=150,
        verbose_name="Название раздела",
        help_text="Укажите название раздела",
    )
    description = models.TextField(
        verbose_name="Описание раздела", help_text="Укажите описание раздела", **NULLABLE
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Разделы"


class Material(models.Model):
    title = models.CharField(
        max_length=150,
        help_text="Укажите название материала",
        verbose_name="Название материала",
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name="materials",
        help_text="Выберите раздел",
        verbose_name="Раздел",
        **NULLABLE,
    )

    contents = models.TextField(
        verbose_name="Содержание материала", help_text="Укажите содержание материала", **NULLABLE
    )
    image = models.ImageField(
        upload_to="materials/preview",
        verbose_name="Превью",
        help_text="Загрузите фото",
        **NULLABLE,
    )

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Материал"
        verbose_name_plural = "Материалы"

materials/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from materials.models import Category, Material
from django.views.generic import View, ListView, DetailView


class HomeListView(ListView):
    model = Category
    template_name = 'materials/index.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return Category.objects.all()


class MaterialsView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        category = Category.objects.get(pk=pk)
        materials = Material.objects.filter(category=category)
        context = {
            "materials": materials,
        }
        return render(request, 'materials/materials.html', context)


class MaterialDetailView(LoginRequiredMixin, DetailView):
    model = Material

materials/templates/materials/includes/inc_footer_menu.html
<div class="row">
    <div class="col-12 col-md">
        SelfLearning
        <small class="d-block mb-3 text-muted">&copy; 2023-{% now 'Y' %}</small>
    </div>
    <div class="col-6 col-md">
        <h5>Разделы</h5>
        <ul class="list-unstyled text-small">
            {% for object in chapters %}
            <li>
                <a class="text-muted" href="{% url 'materials:materials' object.pk %}">{{ object.name }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-6 col-md">
        <h5>Дополнительно</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Мы пишем</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
        <h5>О нас</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Контакты</a></li>
        </ul>
    </div>
</div>

materials/templates/materials/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">SelfLearning</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'materials:home' %}">Главная</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Проект самообучения</h1>
    <p class="lead">Проект самообучения - это отличный вариант получить образование по современным специальностям
        не выходя из дома. </p>
</div>